# Generated by Django 2.2.7 on 2019-11-10 08:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('djblockchain', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='contract',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='call_set', to='djblockchain.Transaction'),
        ),
    ]
