# Generated by Django 2.2.5 on 2019-11-11 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djblockchain', '0004_auto_20191111_1740'),
    ]

    operations = [
        migrations.AddField(
            model_name='blockchain',
            name='explorer',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
