# Generated by Django 2.2.9 on 2020-01-09 16:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('djblockchain', '0008_blockchain_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='contract',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='call_set', to='djblockchain.Transaction'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='function',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
