# Generated by Django 2.2.9 on 2020-01-23 09:28

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('djblockchain', '0009_auto_20200109_1647'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='args',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=list, null=True),
        ),
    ]
