# Generated by Django 2.2.3 on 2020-02-25 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('djblockchain', '0010_auto_20200123_0928'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='account',
            unique_together=set(),
        ),
    ]
