# Generated by Django 3.0.5 on 2020-04-17 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djblockchain', '0011_remove_address_unicity_constraint'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='txhash',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
