# Generated by Django 3.0.5 on 2020-05-15 18:01

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('djblockchain', '0013_auto_20200512_2321'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='history',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=[]),
        ),
    ]
