# Generated by Django 2.2.7 on 2019-11-18 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('djblockchain', '0005_blockchain_explorer'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='account',
            unique_together={('blockchain', 'address')},
        ),
    ]
