# Generated by Django 2.2.5 on 2019-11-21 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djblockchain', '0006_unique_blockchain_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='blockchain',
            name='confirmation_blocks',
            field=models.IntegerField(default=0),
        ),
    ]
