# Generated by Django 3.0.5 on 2020-05-12 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djblockchain', '0012_txhash_unique'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='error',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='state',
            field=models.CharField(choices=[('held', 'Held'), ('deploy', 'To deploy'), ('watch', 'Watching'), ('postdeploy', 'Post-deploying'), ('done', 'Finished')], default='held', max_length=200),
        ),
    ]
