# Generated by Django 3.0.6 on 2020-05-22 12:04

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djblockchain', '0014_transaction_history'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='accepted',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='hold',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='status',
        ),
        migrations.AlterField(
            model_name='blockchain',
            name='provider_class',
            field=models.CharField(choices=[('eqs_sft.ethereum.Provider', 'Ethereum'), ('eqs_sft.tezos.Provider', 'Tezos')], default='djblockchain.fake.Provider', max_length=255),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='history',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='state',
            field=models.CharField(choices=[('held', 'Held'), ('deploy', 'To deploy'), ('deploying', 'Deploying'), ('watch', 'To watch'), ('watching', 'Watching'), ('postdeploy', 'To post-deploy'), ('postdeploying', 'Post-deploying'), ('done', 'Finished')], default='held', max_length=200),
        ),
    ]
