# Generated by Django 3.0.10 on 2020-09-11 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djblockchain', '0015_remove_deprecated_hold_status_accepted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='state',
            field=models.CharField(choices=[('held', 'Held'), ('deploy', 'To deploy'), ('deploying', 'Deploying'), ('watch', 'To watch'), ('watching', 'Watching'), ('postdeploy', 'To post-deploy'), ('postdeploying', 'Post-deploying'), ('done', 'Finished')], db_index=True, default='held', max_length=200),
        ),
    ]
