# Generated by Django 3.1.4 on 2021-01-26 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djblockchain', '0016_index_transaction_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blockchain',
            name='provider_class',
            field=models.CharField(choices=[('djblockchain.ethereum.Provider', 'Ethereum'), ('djblockchain.tezos.Provider', 'Tezos'), ('djblockchain.fake.Provider', 'Test'), ('djblockchain.fake.FailDeploy', 'Test that fails deploy'), ('djblockchain.fake.FailWatch', 'Test that fails watch')], default='djblockchain.fake.Provider', max_length=255),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='args',
            field=models.JSONField(default=list, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='history',
            field=models.JSONField(default=list),
        ),
    ]
