# Generated by Django 3.2 on 2021-04-07 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djblockchain', '0017_jsonfield'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='block',
        ),
        migrations.AddField(
            model_name='transaction',
            name='contract_code',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='Block',
        ),
    ]
