# Generated by Django 3.2 on 2021-04-08 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djtezos', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='contract_code',
            new_name='contract_source',
        ),
        migrations.AddField(
            model_name='transaction',
            name='contract_micheline',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
