# Generated by Django 3.2 on 2021-05-13 15:59

from django.db import migrations, models


def null_amount(apps, schema_editor):
    Transaction = apps.get_model('djtezos', 'Transaction')
    Transaction.objects.filter(amount=0).update(amount=None)


class Migration(migrations.Migration):

    dependencies = [
        ('djtezos', '0003_account_created_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='amount',
            field=models.PositiveIntegerField(blank=True, db_index=True, help_text='Amount in xTZ', null=True),
        ),
        migrations.RunPython(null_amount),
    ]
