# Generated by Django 3.1.6 on 2021-05-23 13:55

from django.db import migrations, models
import django.db.models.deletion


def remove_null_sender(apps, schema_editor):
    Transaction = apps.get_model('djtezos', 'Transaction')
    Transaction.objects.filter(sender=None).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('djtezos', '0005_alter_transaction_function'),
    ]

    operations = [
        migrations.RunPython(remove_null_sender),
        migrations.AlterField(
            model_name='transaction',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions_sent', to='djtezos.account'),
        ),
    ]
