# Generated by Django 3.2 on 2021-05-24 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djtezos', '0005_alter_transaction_function'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='args_mich',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
