# Generated by Django 3.2 on 2021-05-24 20:02

from django.db import migrations, models


def account_name(apps, schema_editor):
    Account = apps.get_model('djtezos', 'account')
    for account in Account.objects.filter(name='default'):
        account.name = account.address
        account.save()


class Migration(migrations.Migration):

    dependencies = [
        ('djtezos', '0007_account_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='name',
            field=models.CharField(default='default', max_length=100),
            preserve_default=False,
        ),
        migrations.RunPython(account_name),
    ]
