# Generated by Django 3.2 on 2021-05-24 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djtezos', '0008_account_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='level',
            field=models.PositiveIntegerField(blank=True, db_index=True, null=True),
        ),
    ]
