# Generated by Django 3.2 on 2021-05-24 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djtezos', '0009_transaction_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='blockchain',
            name='max_level',
            field=models.PositiveIntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='blockchain',
            name='min_level',
            field=models.PositiveIntegerField(blank=True, default=None, null=True),
        ),
    ]
