# Generated by Django 3.2 on 2021-05-25 05:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('spool_auth', '0001_initial'),
        ('djtezos', '0010_levels'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='followers',
            field=models.ManyToManyField(blank=True, to='spool_auth.User'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='receiver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions_received', to='djtezos.account'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='sender',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions_sent', to='djtezos.account'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='state',
            field=models.CharField(choices=[('held', 'Held'), ('deploy', 'To deploy'), ('deploying', 'Deploying'), ('deploy-aborted', 'Deploy aborted'), ('watch', 'To watch'), ('watching', 'Watching'), ('watch-aborted', 'Watch aborted'), ('done', 'Finished')], db_index=True, default='held', max_length=200),
        ),
    ]
