# Generated by Django 3.2 on 2021-05-25 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djtezos', '0011_contract_import'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='searched',
            field=models.ManyToManyField(blank=True, to='djtezos.Blockchain'),
        ),
    ]
