# Generated by Django 3.2 on 2021-06-06 16:31

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djtezos', '0011_last_fail'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='users',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
